baseurl = "http://elliottbeaty.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ejb_portfolio"
canonifyurls = "true"
[[menu.main]]
	name = "home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "about"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "portfolio"
	url = "/projects/"
	weight = 3
[[menu.main]]
	name = "contact"
	url = "/contact/"
	weight = 4



